config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"

  devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: 'omniauth_callbacks' }
  resources :picks
  resources :games
  resources :weeks
  resources :seasons
  resources :teams
  resources :picksets do
    get 'permalink', on: :member
  end
  # root to: "seasons#show"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup
end

app/models/pickset.rb
# == Schema Information
#
# Table name: picksets
#
#  id        :integer          not null, primary key
#  season_id :integer
#  user_id   :integer
#  name      :string(255)
#
class Pickset < ActiveRecord::Base
  belongs_to :user
  belongs_to :season
  has_many :picks

  accepts_nested_attributes_for :picks, allow_destroy: true

  def wins_for(team)
    picks.where(winning_team_id: team.id).count
  end

  def losses_for(team)
    picks.where(losing_team_id: team.id).count
  end

  def user_picks(user_id = current_user.id)
    picks.where(user: user_id)
  end
end

app/controllers/picksets_controller.rb
# Pick Sets
class PicksetsController < ApplicationController
  before_action :set_pickset, only: [:show, :edit, :update, :destroy]

  # GET /picksets
  def index
    @picksets = Pickset.all
  end

  # GET /picksets/1
  def show
      @pickset_season = @season.to_json
      @grouped_teams = Team.by_conference
  end

  # GET /picksets/new
  def new
    @pickset = Pickset.new
  end

  # GET /picksets/1/edit
  def edit
  end

  # POST /picksets
  def create
    @pickset ||= Pickset.new(pickset_params)

    if @pickset.save
      redirect_to root_path, notice: "Pickset was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /picksets/1
  def update
    if @pickset.update(pickset_params)
      redirect_to root_path, notice: 'Pickset was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /picksets/1
  def destroy
    @pickset.destroy
    redirect_to root_path, notice: 'Pickset was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pickset
    @pickset = Pickset.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def pickset_params
    params.require(:pickset).permit(:season_id, :user_id, :name)
  end
end

app/views/picksets/_form.html.haml
= simple_form_for(@pickset) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :user_id, value: current_user.id
    = f.hidden_field :season_id, value: @season.id
    = f.text_field :name
  .form-actions
    = f.button :submit

app/views/picksets/_standings.html.haml
#standings
  - @grouped_teams.each do |conf, div_groups|
    %div{ class: "conference #{conf}" }
      %h1= conf.upcase
      - div_groups.each do |division, teams|
        .divisions
          %h2= division.titleize
          %table.teams
            %tr
              %th
                &nbsp;
              %th.record
                %strong
                  W
              %th.record
                %strong
                  L
            - teams.each do |team|
              %tr.team
                %td
                  = team.name
                %td.record
                  = @pickset.wins_for(team)
                %td.record
                  = @pickset.losses_for(team)

app/views/picksets/edit.html.erb
<h1>Editing Pickset</h1>

<%= render 'form' %>

<%= link_to 'Show', @pickset %> |
<%= link_to 'Back', picksets_path %>

app/views/picksets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Picksets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @picksets.each do |pickset| %>
      <tr>
        <td><%= link_to 'Show', pickset %></td>
        <td><%= link_to 'Edit', edit_pickset_path(pickset) %></td>
        <td><%= link_to 'Destroy', pickset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pickset', new_pickset_path %>

app/views/picksets/new.html.erb
<h1>New Pickset</h1>

<%= render 'form' %>

<%= link_to 'Back', picksets_path %>

app/views/picksets/show.html.haml
=#render partial: 'standings'
=#render @season.weeks
=react_component 'Pickset', pickset_season: @pickset_season

= link_to 'Edit', edit_pickset_path(@pickset)
|
= link_to 'Back', picksets_path